nervous coding

fizz buzz

In [27]:
#fizzbuzz takes precedence
#then fizz and buzz
x=1
lst=[]
out=''
while x <=100:
    if x%3==0:
        out+='fizz'
        lst.append(out)
    elif x%5==0:
        out+='buzz'
        lst.append(out)
    else:
        #print(x)
        lst.append(x)
    out=''
    x+=1

In [28]:
new_lst

[1,
 2,
 'fizz',
 4,
 'buzz',
 'fizz',
 7,
 8,
 'fizz',
 'buzz',
 11,
 'fizz',
 13,
 14,
 'fizzbuzz',
 16,
 17,
 'fizz',
 19,
 'buzz',
 'fizz',
 22,
 23,
 'fizz',
 'buzz',
 26,
 'fizz',
 28,
 29,
 'fizzbuzz',
 31,
 32,
 'fizz',
 34,
 'buzz',
 'fizz',
 37,
 38,
 'fizz',
 'buzz',
 41,
 'fizz',
 43,
 44,
 'fizzbuzz',
 46,
 47,
 'fizz',
 49,
 'buzz',
 'fizz',
 52,
 53,
 'fizz',
 'buzz',
 56,
 'fizz',
 58,
 59,
 'fizzbuzz',
 61,
 62,
 'fizz',
 64,
 'buzz',
 'fizz',
 67,
 68,
 'fizz',
 'buzz',
 71,
 'fizz',
 73,
 74,
 'fizzbuzz',
 76,
 77,
 'fizz',
 79,
 'buzz',
 'fizz',
 82,
 83,
 'fizz',
 'buzz',
 86,
 'fizz',
 88,
 89,
 'fizzbuzz',
 91,
 92,
 'fizz',
 94,
 'buzz',
 'fizz',
 97,
 98,
 'fizz',
 'buzz']

In [2]:
import numpy as np

In [5]:
a = np.random.randn(3,3)
b= np.random.randn(3,1)
c=a*b
c.shape

(3, 3)

In [6]:
print(c)

[[-0.46994991  0.09224717 -0.48789704]
 [ 0.27379405  0.11829277  0.16490788]
 [-0.23022932  0.13636766 -1.36238395]]


In [7]:
print(a)

[[-1.98708487  0.39004786 -2.06297055]
 [ 1.33286439  0.5758643   0.8027926 ]
 [-0.29577828  0.17519312 -1.7502705 ]]


In [8]:
print(b)

[[0.23650218]
 [0.20541778]
 [0.7783848 ]]


In [13]:
a=np.arange(1,10,1).reshape(3,3)
b=np.arange(2,8,2).reshape(3,1)

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
b

array([[2],
       [4],
       [6]])

In [16]:
a*b

array([[ 2,  4,  6],
       [16, 20, 24],
       [42, 48, 54]])

In [3]:
A= np.random.randn(4,3)
B= np.sum(A, axis=1, keepdims=True)
B.shape

(4, 1)